#!/usr/bin/env python
"""This script wraps ScoutSuite and prints dangerous findings"""


from os import system
from subprocess import call
# from json import load

from ./ScoutSuite.__main__ import run_from_cli

if __name__ == "__main__":
    sys.exit(run_from_cli())

